// Code generated by "stringer -type=ReturnCode"; DO NOT EDIT.

package code

// ----- ---- --- -- -
// Copyright 2019 Oneiro NA, Inc. All Rights Reserved.
//
// Licensed under the Apache License 2.0 (the "License").  You may not use
// this file except in compliance with the License.  You can obtain a copy
// in the file LICENSE in the source distribution or at
// https://www.apache.org/licenses/LICENSE-2.0.txt
// - -- --- ---- -----

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[OK-0]
	_ = x[InvalidTransaction-1]
	_ = x[ErrorApplyingTransaction-2]
	_ = x[EncodingError-3]
	_ = x[QueryError-4]
	_ = x[IndexingError-5]
	_ = x[InvalidNodeState-6]
}

const _ReturnCode_name = "OKInvalidTransactionErrorApplyingTransactionEncodingErrorQueryErrorIndexingErrorInvalidNodeState"

var _ReturnCode_index = [...]uint8{0, 2, 20, 44, 57, 67, 80, 96}

func (i ReturnCode) String() string {
	if i >= ReturnCode(len(_ReturnCode_index)-1) {
		return "ReturnCode(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _ReturnCode_name[_ReturnCode_index[i]:_ReturnCode_index[i+1]]
}
